package test.UnitTests;

public class ShopOwnerUnitTest {
    //TODO IMPLEMENT SHOP OWNER: ADD AND REMOVE PRODUCTS AND THEIR DETAILS.
    //TODO IMPLEMENT CLOSE SHOP(SHOP OWNER)
    //TODO IMPLEMENT ASK FOR DATA ON SHOP EMPLOYEES(FOR OWNER ONLY)
    //TODO PURCHASE HISTORY OF THE SHOP(SHOP OWNER)

}
