package com.example.server.UnitTests;

public class VisitorUnitTest {
    //TODO IMPLEMENT: VISITOR AND MEMBER , LOGIN , LOGOUT, REGISTER.
    //TODO INFORMATION ON SHOPS AND ITS ITEMS, SEARCH PRODUCTS BY ..
    //TODO IMPLEMENT SAVE ITEM IN SHOPPING CART.
    //TODO IMPLEMENT CHECK SHOPPING CART CONTENT AND EDIT AMOUNTS
    //TODO IMPLEMENT CART PURCHASE
}
